<script src="{{asset('assets/apps/portal/fronted/js/vendor/modernizr-3.6.0.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/vendor/jquery-1.12.4.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/slick.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/waypoints.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/jquery.counterup.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/jquery.nice-select.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/jquery.nice-number.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/jquery.countdown.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/validator.min.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/ajax-contact.js')}}"></script>
<script src="{{asset('assets/apps/portal/fronted/js/main.js')}}"></script>
{{--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDC3Ip9iVC0nIxC6V14CKLQ1HZNF_65qEQ"></script>--}}
<script src="{{asset('assets/apps/portal/fronted/js/map-script.js')}}"></script>
