<?php

namespace App\Exports\Graduate;

use App\Models\Graduate\Student;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\DefaultValueBinder;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\DataType;

class StudentExport extends DefaultValueBinder implements FromCollection, WithHeadings
{
    public function bindValue(Cell $cell, $value)
    {
        $cell->setValueExplicit($value, DataType::TYPE_STRING2);
        return parent::bindValue($cell, $value); // TODO: Change the autogenerated stub
    }

    public function collection()
    {
        return Student::orderBy('student_class')->orderBy('student_name')->get();
    }

    public function startCell() : string
    {
        return 'B!';
    }

    public function headings(): array
    {
        return ['no', 'nama_lengkap', 'nisn', 'nism', 'no_ujian', 'kelas', 'tempat_lahir', 'tanggal_lahir', 'jk', 'alamat', 'nama_ayah', 'nama_ibu'];
    }
}
